Added tsk1 as pull request(correctlier)
IvanVuzh/progCourse pull request #18
Opened 2021-02-15 13:11 UTC by IvanVuzh

2021-02-15 17:54 UTC, incora-dev requested changes

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Collection.cs
> +                JsonSchema schema = new JsonSchema();
Use json serializer here as well.

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Collection.cs
> +                //Console.WriteLine(json_for_order);
remove comments

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Collection.cs
> +            //string res = "";
remove comments

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Collection.cs
> +                //order_collection.Sort( (x, y) =>
remove comments

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Order.cs
> +                if (Validation.check_id_or_amount(value))
use ternary operator

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Order.cs
> +                if (Validation.check_id_or_amount(value))
use ternary operator

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Order.cs
> +                if (Validation.status_check(value))
use ternary operator

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Order.cs
> +                if (Validation.check_discount(value))
use ternary operator

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Order.cs
> +                if (Validation.date_check(value))
use ternary operator

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Order.cs
> +                if (Validation.date_check(value))
use ternary operator

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Order.cs
> +            bool res = true;
unnecessary code (this method and public Order() as well)

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Order.cs
> +            Console.WriteLine("Enter id:");
remove copy paste

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Validation.cs
> +                if (Convert.ToInt32(id) < 1)
return !(Convert.ToInt32(id) < 1);

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Validation.cs
> +                if (Convert.ToInt32(id) < 1)
same for all methods

2021-02-15 17:54 UTC, incora-dev commented on Csharp tasks/Task 1/Validation.cs
> +            if (order_status == "paid" || order_status == "not paid" || order_status == "refunded")
make enum for order_status.

2021-02-22 18:46 UTC, tetianastoyko approved these changes

2021-03-13 16:45 UTC, merged